# Book settings
logo: Logo2.png
title: Aircraft Flight Mechanics by Harry Smith, PhD
author: Harry Smith


latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url                       : https://github.com/aeronauty/Aircraft-Flight-Mechanics

# HTML
html:
  use_repository_button     : true
  use_issues_button         : true
  use_edit_page_button      : true  # Whether to add an "edit this page" button to pages. 
  extra_navbar: <div><script data-ad-client="ca-pub-5107176300009857" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script></div>
  google_analytics_id: UA-178506186-1
  extra_footer: |
        <div>
            <a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/"><img alt="Creative Commons Licence" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-nd/4.0/88x31.png" /></a><br /><span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">Aircraft Flight Mechanics</span> by <a xmlns:cc="http://creativecommons.org/ns#" href="www.aircraftflightmechanics.com" property="cc:attributionName" rel="cc:attributionURL">Harry Smith</a> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/">Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License</a>.<br />Based on a work at <a xmlns:dct="http://purl.org/dc/terms/" href="www.aircraftflightmechanics.com" rel="dct:source">www.aircraftflightmechanics.com</a>.
        </div>

# Configure your Binder links, such as the URL of the BinderHub.
launch_buttons:
  binderhub_url             : https://mybinder.org
  thebe                     : true  # Add a thebe button to pages (requires the repository to run on Binder)


execute_notebooks: force
jupyter_execute_notebooks: force

sphinx:
  extra_extensions:
  - sphinx_tabs.tabs

